[theme]
primaryColor = "#FFD700"
backgroundColor = "#02050E"
secondaryBackgroundColor = "#0A111F"
textColor = "#ECE8E1"
font = "sans serif"

[server]
maxUploadSize = 50
address = "0.0.0.0"

[browser]
gatherUsageStats = false
